### ISSUE TITLE
Any plans to continue development?

### ISSUE THREAD

**Issue by kurtschlatzer** [FlightByCanto/Flight-Wordpress-Plugin#6]
Dead plugin? Paying Flight customer asking.

**Comment by CantoDAM** [comment]
Hi there. We have been working hard to provide a functional re-build using ReactJS which was available on a separate [branch](https://github.com/FlightByCanto/Flight-Wordpress-Plugin/tree/react). We have successfully merged back to master and also provided v2.0 of the [Flight Wordpress Plugin on the WP SVN](https://wordpress.org/plugins/flight-by-canto/)
